### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Assasingus14** [skyjay1/GreekFantasy#27] opened 2021-01-04 01:36 UTC
Got this crash log when using it with my modpack. It says that it ran into an error loading some class
[crash-2021-01-04_01.30.42-fml.txt](https://github.com/skyjay1/GreekFantasy/files/5762631/crash-2021-01-04_01.30.42-fml.txt)

**Comment by skyjay1** [comment] 2021-01-04 17:37
Duplicate of #26

**Closed by skyjay1** 2021-01-04 17:37 UTC
Labels: duplicate
