### ISSUE TITLE
Blame Report

### ISSUE THREAD

**Issue by Tyrius1** [skyjay1/GreekFantasy#8] opened 2020-12-10 17:10 UTC
Not actually a noticed issue. Just going through my logs with blame installed and passing out some Blame Reports:
https://pastebin.com/6NgM2pvg

**Comment by skyjay1** [comment] 2020-12-10 23:28
Duplicate of #7 , expect this to be fixed in the next release (tomorrow, if I have time for testing)

**Closed by skyjay1** 2020-12-10 23:28 UTC
Labels: duplicate
