### ISSUE TITLE
Start up client crassh

### ISSUE THREAD

**Issue by drwad** [skyjay1/GreekFantasy#121] opened 2022-10-18 13:55 UTC
[crash-2022-10-18_10.52.45-client.txt](https://github.com/skyjay1/GreekFantasy/files/9811116/crash-2022-10-18_10.52.45-client.txt)

**Comment by skyjay1** [comment] 2022-10-18 17:57
Duplicate of #111 
Please inform the Epic Knights developers that it is not safe to convert modded banner names to resource locations.

**Closed as completed by skyjay1** 2022-10-18 17:57 UTC
Labels: duplicate

**Comment by drwad** [comment] 2022-10-18 18:10
thanks for reply
