### ISSUE TITLE
Total crash related to grey wall banners

### ISSUE THREAD

**Issue by DarkenRal10** [skyjay1/GreekFantasy#133] opened 2023-03-26 23:09 UTC
Hi, I have experienced a crash where when exploring a Minecraft world, after exploring for a while, a chunk will be rendered, I'm not sure with what, and then a CTD. I took a look into other opened issues, and I saw someone who had pretty much the same crash logs relating to a grey wall banner crash. I saw that this seems to be related to the Arachne Pit generation. I am playing on the most recent 1.18.2 version. (18.2.9). I was wondering if there was a way for this to be fixed, or is there somewhere in the config where I can disable this generation. I looked into the config but could not see an option for this. I also included the crash file. 

I am using forge version 40.2.0

Thanks! 

Edit: So I removed the mod, and was able to reload the world. It looks like there was an underwater cave spider spawner dungeon with two grey banners which was probably causing the crashing. I'm not sure if that is what the Arachne pit is supposed to be? 

[crash-2023-03-26_15.13.18-client.txt](https://github.com/skyjay1/GreekFantasy/files/11073306/crash-2023-03-26_15.13.18-client.txt)

**Comment by skyjay1** [comment] 2023-03-31 16:58
Duplicate of #95 #98 #101 
Forge changed some things about custom banner patterns in the 1.18 versions which caused a lot of problems

**Closed as completed by skyjay1** 2023-03-31 16:58 UTC
Labels: duplicate
