### ISSUE TITLE
Banner crashing game

### ISSUE THREAD

**Issue by littlepianist** [skyjay1/GreekFantasy#98] opened 2022-08-18 14:15 UTC
[crash-2022-08-18_21.55.44-client.txt](https://github.com/skyjay1/GreekFantasy/files/9374600/crash-2022-08-18_21.55.44-client.txt)

**Comment by skyjay1** [comment] 2022-08-18 16:27
Duplicate of #95 
I finally found the problem, Forge changed how banners are registered in 40.1.48 and I've been using 40.1.44
The next update should fix this.

**Comment by skyjay1** [comment] 2022-08-18 18:11
Fixed in 18.2.4

**Closed as completed by skyjay1** 2022-08-18 18:11 UTC
Labels: bug, duplicate
