### ISSUE TITLE
Have to re-offer Hermes Boots every time I want to fly. Edit: it seems i have to stay at level 10 to fly but my favor gets reset returning from the end

### ISSUE THREAD

**Issue by Redwtre** [skyjay1/GreekFantasy#60] opened 2021-06-19 05:53 UTC
As the title states, every time my favor with Hermes goes below level 10, I can not fly with the Hermes Boots even though they have flying on them. The only fix I found is getting my favor with Hermes to level 10 and re-offering the boots, with the enchantment already on them, then the game will allow me to fly for only as long as I have level 10 favor with Hermes.

**Comment by skyjay1** [comment] 2021-06-22 02:20
Duplicate of #61

**Closed by skyjay1** 2021-06-22 02:20 UTC
Labels: bug, duplicate
